"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowDownUp, Calculator, Check, Clipboard, Clock3, HeartHandshake, MapPin, MessageSquareText, RefreshCcw, Route, Send, ShieldCheck, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

type Suggestion = { id: string; title: string; label: string; region: string; position: { lat: number; lng: number } }; type Place = { label: string; region?: string; position?: { lat: number; lng: number } }; type RouteData = { meters: number; seconds: number }; type Result = { from: string; to: string; route: RouteData; rate: number; analytics: { fromRegion: string; toRegion: string } };
const money = new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }); const km = (meters: number) => Math.round(meters / 1000); const duration = (seconds: number) => { const total = Math.round(seconds / 60), h = Math.floor(total / 60), m = total % 60; return h ? `${h} ч ${m ? `${m} мин` : ""}`.trim() : `${m} мин`; }; const rideCost = (route: RouteData, rate: number) => Math.round((route.meters / 1000) * rate);

function AddressField({ label, value, onChange, placeholder }: { label: string; value: Place; onChange: (place: Place) => void; placeholder: string }) {
  const [items, setItems] = useState<Suggestion[]>([]), [open, setOpen] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const update = (text: string) => { onChange({ label: text }); setOpen(true); if (timer.current) clearTimeout(timer.current); if (text.trim().length < 3) { setItems([]); return; } timer.current = setTimeout(async () => { try { const r = await fetch(`/api/suggest?q=${encodeURIComponent(text)}`), d = await r.json() as { items?: Suggestion[] }; setItems(d.items ?? []); } catch { setItems([]); } }, 280); };
  return <div className="relative"><Label className="mb-1.5 block text-sm font-semibold">{label}</Label><div className="relative"><MapPin className="pointer-events-none absolute left-3.5 top-1/2 size-4.5 -translate-y-1/2 text-slate-400" /><Input value={value.label} onChange={(e) => update(e.target.value)} onFocus={() => setOpen(true)} onBlur={() => setTimeout(() => setOpen(false), 150)} placeholder={placeholder} autoComplete="off" className="h-12 rounded-xl border-slate-200 bg-white pl-11 pr-3 text-[15px] shadow-sm dark:border-slate-700 dark:bg-slate-900" /></div>{open && items.length > 0 && <div role="listbox" className="absolute z-30 mt-2 max-h-72 w-full overflow-auto rounded-2xl border border-slate-200 bg-white p-1 shadow-xl dark:border-slate-700 dark:bg-slate-900">{items.map((item) => <button key={item.id} type="button" role="option" onMouseDown={() => { onChange({ label: item.label, region: item.region, position: item.position }); setOpen(false); }} className="block w-full rounded-xl px-3 py-3 text-left hover:bg-slate-100 dark:hover:bg-slate-800"><span className="block font-medium">{item.title}</span><span className="block truncate text-sm text-slate-500">{item.label}</span></button>)}</div>}</div>;
}
function RouteCard({ route, rate }: { route: RouteData; rate: number }) { const fare = rideCost(route, rate); return <section className="route-card route-fast"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-bold">Маршрут поездки</h2><span className="route-pill">{km(route.meters)} км</span></div><div className="mt-3 flex items-center gap-2 text-slate-600 dark:text-slate-300"><Clock3 className="size-4" />{duration(route.seconds)}</div><dl className="mt-5 grid gap-3 text-[15px]"><div><dt>Расстояние</dt><dd>{km(route.meters)} км</dd></div><div><dt>Тариф</dt><dd>{money.format(rate)} ₽/км</dd></div><div className="total"><dt>Стоимость поездки</dt><dd>{money.format(fare)} ₽</dd></div></dl></section>; }

function FeedbackForm() {
  const [category, setCategory] = useState("Улучшение калькулятора");
  const [message, setMessage] = useState("");
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (message.trim().length < 10) { setStatus("error"); return; }
    setStatus("sending");
    try {
      const response = await fetch("/api/collect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "feedback", category, message, website: "" }) });
      if (!response.ok) throw new Error();
      setMessage(""); setStatus("sent");
    } catch { setStatus("error"); }
  };
  return <section className="panel mt-5" aria-labelledby="ideas-title"><div className="section-icon"><MessageSquareText className="size-5" /></div><h2 id="ideas-title" className="mt-4 text-xl font-extrabold">Предложить улучшение</h2><p className="mt-1 text-sm leading-relaxed text-slate-500 dark:text-slate-400">Расскажите, чего не хватает калькулятору или что стоит сделать следующим.</p><form onSubmit={submit} className="mt-5 space-y-3"><Label htmlFor="category">Категория</Label><select id="category" value={category} onChange={(e) => setCategory(e.target.value)} className="form-control"><option>Улучшение калькулятора</option><option>Новая функция</option><option>Сообщить об ошибке</option><option>Другое</option></select><Label htmlFor="idea">Ваше предложение</Label><textarea id="idea" value={message} onChange={(e) => { setMessage(e.target.value); if (status !== "idle") setStatus("idle"); }} minLength={10} maxLength={1000} required rows={4} placeholder="Например: добавить расчёт обратной поездки…" className="form-control resize-y" /><div className="flex items-start gap-2 text-xs leading-relaxed text-slate-500"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-emerald-600" /><span>Не указывайте телефон, email и другие персональные данные.</span></div>{status === "sent" && <p role="status" className="text-sm font-semibold text-emerald-600">Спасибо! Предложение сохранено.</p>}{status === "error" && <p role="alert" className="text-sm font-semibold text-red-600">Не удалось отправить. Проверьте текст или попробуйте позже.</p>}<Button type="submit" disabled={status === "sending"} className="h-12 w-full rounded-2xl bg-slate-900 font-bold text-white dark:bg-white dark:text-slate-950">{status === "sending" ? <><RefreshCcw className="size-4 animate-spin" />Отправляем…</> : <><Send className="size-4" />Отправить идею</>}</Button></form></section>;
}

function DonationCard() {
  const url = process.env.NEXT_PUBLIC_DONATION_URL || "https://www.tbank.ru/cf/8cnjvG9c20z";
  return <section className="support-card mt-5" aria-labelledby="support-title"><div className="section-icon support-icon"><HeartHandshake className="size-5" /></div><h2 id="support-title" className="mt-4 text-xl font-extrabold">Поддержать развитие</h2><p className="mt-1 text-sm leading-relaxed text-slate-600 dark:text-slate-300">Добровольная поддержка поможет оплачивать сервисы и добавлять новые возможности.</p>{url ? <Button asChild className="mt-5 h-12 w-full rounded-2xl bg-emerald-600 font-bold text-white hover:bg-emerald-700"><a href={url} target="_blank" rel="noopener noreferrer"><HeartHandshake className="size-4" />Поддержать через СБП</a></Button> : <Button disabled className="mt-5 h-12 w-full rounded-2xl font-bold"><HeartHandshake className="size-4" />СБП скоро появится</Button>}<p className="mt-3 text-center text-xs text-slate-500">Платёжные данные на сайте не вводятся — перевод откроется на защищённой странице банка.</p></section>;
}

export default function Home() {
  const [from, setFrom] = useState<Place>({ label: "" }), [to, setTo] = useState<Place>({ label: "" }), [rate, setRate] = useState("35"), [remember, setRemember] = useState(true), [result, setResult] = useState<Result | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false), [copied, setCopied] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("taxi-rate"); if (saved) setRate(saved); }, []); useEffect(() => { if (remember && Number(rate) > 0) localStorage.setItem("taxi-rate", rate); else if (!remember) localStorage.removeItem("taxi-rate"); }, [rate, remember]);
  useEffect(() => { if (localStorage.getItem("mezhgorod-visit-recorded")) return; void fetch("/api/collect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "visit" }) }).then((response) => { if (response.ok) localStorage.setItem("mezhgorod-visit-recorded", "1"); }).catch(() => undefined); }, []);
  const calculate = async () => { setError(""); setResult(null); const numericRate = Number(rate.replace(",", ".")); if (!from.label.trim() || !to.label.trim()) { setError("Укажите, откуда и куда нужно ехать"); return; } if (!Number.isFinite(numericRate) || numericRate <= 0) { setError("Введите корректную стоимость 1 км"); return; } setLoading(true); try { const response = await fetch("/api/calculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ from, to, rate: numericRate }) }), data = await response.json() as Result & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Не удалось выполнить расчёт"); setResult(data); void fetch("/api/collect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "route", fromRegion: data.analytics.fromRegion, toRegion: data.analytics.toRegion, distanceKm: km(data.route.meters), durationMin: Math.round(data.route.seconds / 60), rate: data.rate, total: rideCost(data.route, data.rate) }) }).catch(() => undefined); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось выполнить расчёт"); } finally { setLoading(false); } };
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: unknown, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    void Promise.resolve(context.registerTool({
      name: "stage_trip_calculation", title: "Заполнить расчёт поездки", description: "Заполняет точки отправления, назначения и тариф в видимом калькуляторе. После этого пользователь может проверить данные и нажать «Рассчитать».",
      inputSchema: { type: "object", properties: { from: { type: "string" }, to: { type: "string" }, rate: { type: "number", exclusiveMinimum: 0 } }, required: ["from", "to", "rate"], additionalProperties: false },
      annotations: { readOnlyHint: false, untrustedContentHint: false },
      execute(input: unknown) { const value = input as { from?: unknown; to?: unknown; rate?: unknown }; if (typeof value.from !== "string" || typeof value.to !== "string" || typeof value.rate !== "number" || value.rate <= 0) throw new Error("Некорректные параметры поездки"); setFrom({ label: value.from }); setTo({ label: value.to }); setRate(String(value.rate)); setResult(null); setError(""); return { status: "ready", from: value.from, to: value.to, rate: value.rate }; }
    }, { signal: lifecycle.signal })).catch(() => undefined);
    return () => lifecycle.abort();
  }, []);
  const copy = async () => { if (!result) return; const fare = rideCost(result.route, result.rate); const text = `${result.from} → ${result.to}\n${km(result.route.meters)} км, ${duration(result.route.seconds)}\nТариф ${money.format(result.rate)} ₽/км\nСтоимость поездки ${money.format(fare)} ₽`; await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  const reset = () => { setFrom({ label: "" }); setTo({ label: "" }); setResult(null); setError(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <main className="min-h-screen px-3 py-3 sm:px-6 sm:py-5"><div className="mx-auto max-w-3xl"><header className="mb-3 flex items-center gap-3"><div className="logo compact-logo"><Route className="size-5" /></div><div><h1 className="text-lg font-extrabold tracking-tight sm:text-xl">Расчёт межгорода</h1><p className="text-xs text-slate-500 dark:text-slate-400">Маршрут и цена за несколько секунд</p></div></header><section className="panel calculator-panel"><div className="space-y-2.5"><AddressField label="Откуда" value={from} onChange={setFrom} placeholder="Город, адрес, аэропорт…" /><div className="flex justify-center"><Button type="button" variant="outline" aria-label="Поменять точки местами" title="Поменять местами" onClick={() => { const old = from; setFrom(to); setTo(old); }} className="h-8 rounded-full px-3 text-xs"><ArrowDownUp className="size-3.5" />Поменять местами</Button></div><AddressField label="Куда" value={to} onChange={setTo} placeholder="Город, адрес, гостиница…" /><div><Label htmlFor="rate" className="mb-1.5 block text-sm font-semibold">Стоимость 1 км</Label><div className="relative"><WalletCards className="pointer-events-none absolute left-3.5 top-1/2 size-4.5 -translate-y-1/2 text-slate-400" /><Input id="rate" inputMode="decimal" value={rate} onChange={(e) => setRate(e.target.value)} className="h-12 rounded-xl border-slate-200 bg-white pl-11 pr-17 text-base font-semibold shadow-sm dark:border-slate-700 dark:bg-slate-900" /><span className="absolute right-3.5 top-1/2 -translate-y-1/2 text-sm text-slate-500">₽/км</span></div></div><div className="flex items-center justify-between rounded-xl bg-slate-100 px-3 py-2 dark:bg-slate-800"><Label htmlFor="remember" className="cursor-pointer text-xs sm:text-sm">Запомнить тариф</Label><Switch id="remember" checked={remember} onCheckedChange={setRemember} /></div>{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300">{error}</div>}<Button onClick={calculate} disabled={loading} className="h-12 w-full rounded-xl bg-blue-600 text-[15px] font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700">{loading ? <><RefreshCcw className="size-4.5 animate-spin" />Строим маршрут…</> : <><Calculator className="size-4.5" />Рассчитать</>}</Button></div><p className="mt-2.5 text-center text-[11px] leading-snug text-slate-500">Ориентировочно, без платных дорог и дополнительных расходов.</p></section>
      {result && <div className="mt-4 space-y-3" aria-live="polite"><div className="px-1 text-sm font-bold">{result.from} <span className="text-slate-400">→</span> {result.to}</div><RouteCard route={result.route} rate={result.rate} /><div className="grid gap-2 sm:grid-cols-2"><Button onClick={copy} className="h-12 rounded-xl bg-slate-900 text-sm font-bold text-white hover:bg-slate-800 dark:bg-white dark:text-slate-950">{copied ? <><Check className="size-4" />Скопировано</> : <><Clipboard className="size-4" />Скопировать расчёт</>}</Button><Button onClick={reset} variant="outline" className="h-12 rounded-xl text-sm font-bold"><RefreshCcw className="size-4" />Новый расчёт</Button></div></div>}<div className="grid gap-4 sm:grid-cols-2"><FeedbackForm /><DonationCard /></div><footer className="py-5 text-center text-[10px] text-slate-400">Адреса: © OpenStreetMap, Photon · маршруты: OSRM</footer></div></main>;
}
